### ISSUE TITLE
qc_api

### ISSUE THREAD

**Issue by quat1024** [quatcraft/quatcraft.github.io#9]
done through a bukkit plugin; exposes some data that server pingers can't like selected player statistics, selected chat statistics (?), "keywords", players online, whitelist, name colors, heads, and more

**Comment by an-OK-squirrel** [comment]
players online ( and heads? ) can be found via server pingers.

**Comment by quat1024** [comment]
No, but it would be nice to have an "official" way to get player names.

I don't think pingers get player heads automatically; if you're referring to cobra's site he goes through Crafatar

**Comment by an-OK-squirrel** [comment]
oh I see.

**Comment by quat1024** [comment]
Closing this issue because we now have https://github.com/quatcraft/qc_api :)

**Comment by Firedrake969** [comment]
A statistics page would be nice too
